Ingredient.create(name: 'lemon')
Ingredient.create(name: 'ice')
Ingredient.create(name: 'mint leaves')
Ingredient.create(name: 'cachaca')
Ingredient.create(name: 'rum')
Ingredient.create(name: 'coca cola')
Ingredient.create(name: 'gin')
Ingredient.create(name: 'tonic water')
Ingredient.create(name: 'vodka')
Ingredient.create(name: 'red bull')
Ingredient.create(name: 'ginger')

Cocktail.create(name: 'Caipirinha')
Cocktail.create(name: 'Gin Tonic')
